apiVersion: apps/v1
kind: Deployment
metadata:
  name: book
  namespace: hibook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z db 5432; do echo waiting for db; sleep 2; done;"]
        - name: wait-for-keycloak
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z keycloak 8080; do echo waiting for keycloak; sleep 2; done;"]
      containers:
        - name: book
          image: book-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/cc_project
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/hibook
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,mappings,metrics,prometheus
            - name: GOOGLE_BOOKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GOOGLE_BOOKS_API_KEY
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: book
  namespace: hibook
spec:
  selector:
    app: book
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
