apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: hibook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh","-c","until nc -z db 5432; do echo waiting for db; sleep 2; done;"]
        - name: wait-for-keycloak
          image: busybox:1.36
          command: ["sh","-c","until nc -z keycloak 8080; do echo waiting for keycloak; sleep 2; done;"]
      containers:
        - name: user
          image: user-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/cc_project
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/hibook
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,mappings,metrics,prometheus
            - name: SERVER_ERROR_INCLUDE_MESSAGE
              value: always
            - name: SERVER_ERROR_INCLUDE_EXCEPTION
              value: "true"
            - name: SERVER_ERROR_INCLUDE_STACKTRACE
              value: always
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB
              value: DEBUG
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: DEBUG

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 25
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: hibook
spec:
  selector:
    app: user
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
